{{- if eq .Values.authType "hybrid_matrix_token" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jitsi-meet.uvs.fullname" . }}-secret
  labels:
    {{- include "jitsi-meet.uvs.labels" . | nindent 4 }}
type: Opaque
stringData:
  UVS_LOG_LEVEL: "{{ .Values.uvs.logLevel | default "info" }}"
  UVS_DISABLE_IP_BLACKLIST: "{{ .Values.uvs.disableIPBlacklist | default "false" }}"
  UVS_ACCESS_TOKEN: "{{ .Values.uvs.accessToken }}"
  UVS_HOMESERVER_URL: "{{ .Values.uvs.homeserverURL }}"
  UVS_PORT: "{{ .Values.uvs.port | default "8080" }}"
{{- end }}