apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prosody.fullname" . }}
  labels:
    {{- include "prosody.labels" . | nindent 4 }}
data:
  ENABLE_END_CONFERENCE: "{{ .Values.enableEndConference | default false }}"
  {{- range $key, $value := .Values.env }}
  {{- if not (kindIs "invalid" $value) }}
  {{ $key }}: {{ tpl $value $ | quote }}
  {{- end }}
  {{- end }}
