{{- if and .Values.overlay.enabled (eq .Values.overlay.mode "v1") (not .Values.overlay.v1.assetsConfigmap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.overlay.v1.fullname" . }}-assets
  labels:
    {{- include "jitsi-meet.overlay.v1.labels" . | nindent 4 }}
binaryData:
{{ range $path, $_ :=  .Files.Glob  (printf "%s/**" (.Values.overlay.v1.assets.path)) }}
  {{ base $path }}: {{ $.Files.Get $path | b64enc | quote }}
{{ end }}
{{- end }}