{{- if .Values.overlay.enabled -}}
{{- $dbHost := "" -}}
{{- $dbUser := "" -}}
{{- $dbDatabase := "" -}}
{{- $dbPassword := "" -}}
{{- $dbRootPassword := "" -}}
{{- if .Values.overlay.database.useExternalDatabase -}}
  {{- $_ := set $ "dbHost" .Values.overlay.database.externalDatabase.host -}}
  {{- $_ := set $ "dbUser" .Values.overlay.database.externalDatabase.user -}}
  {{- $_ := set $ "dbDatabase" .Values.overlay.database.externalDatabase.database -}}
  {{- $_ := set $ "dbPassword" .Values.overlay.database.externalDatabase.password -}}
{{- else -}}
  {{- $_ := set $ "dbHost" (printf "%s.%s.svc.cluster.local" (include "jitsi-meet.overlay.database.fullname" .) .Release.Namespace) -}}
  {{- $_ := set $ "dbUser" .Values.overlay.database.auth.user -}}
  {{- $_ := set $ "dbDatabase" .Values.overlay.database.auth.database -}}
  {{- $_ := set $ "dbPassword" (.Values.overlay.database.auth.password) -}}
  {{- $_ := set $ "dbRootPassword" (.Values.overlay.database.auth.rootPassword) -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jitsi-meet.overlay.database.fullname" . }}-secret
  labels:
    {{- include "jitsi-meet.overlay.database.labels" . | nindent 4 }}
type: Opaque
data:
  {{/* Puisque le secret est utilisé par le MariaDB, on doit forcément laisser la syntaxe par défaut. */}}
  MARIADB_USER: '{{ $.dbUser | b64enc }}'
  MARIADB_DATABASE: '{{ $.dbDatabase | b64enc }}'
  MARIADB_PASSWORD: '{{ $.dbPassword | b64enc }}'
  MARIADB_ROOT_PASSWORD: '{{ $.dbRootPassword | b64enc }}'
  # MARIADB_RANDOM_ROOT_PASSWORD: 'MQo=' # Base64 de "1" pour activer le mot de passe root aléatoire

  {{/* La V3 utilise une syntaxe différente, alors on rajoute les mêmes variables 
    mais sous un autre nom pour que l'overlay puisse y accéder.*/}}
  {{- if eq .Values.overlay.mode "v3" }}
  DB_USERNAME: '{{ $.dbUser | b64enc }}'
  DB_NAME: '{{ $.dbDatabase | b64enc }}'
  DB_PASSWORD: '{{ $.dbPassword | b64enc }}'
  {{- end }}
{{- end }}