{{- if and .Values.overlay.enabled (not .Values.overlay.database.useExternalDatabase) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jitsi-meet.overlay.database.fullname" . }}-secret
  labels:
    {{- include "jitsi-meet.overlay.database.labels" . | nindent 4 }}
type: Opaque
data:
  MARIADB_USER: '{{ .Values.overlay.database.auth.user | b64enc }}'
  MARIADB_DATABASE: '{{ .Values.overlay.database.auth.database | b64enc }}'
  MARIADB_ROOT_PASSWORD: '{{ default (randAlphaNum 16) .Values.overlay.database.auth.rootPassword | b64enc }}'
  MARIADB_PASSWORD: '{{ default (randAlphaNum 16) .Values.overlay.database.auth.password | b64enc }}'
{{- end }}