apiVersion: v1
kind: Secret
metadata:
  name: {{ include "call-nested" (list . "prosody" "prosody.fullname") }}-turn
  labels:
    {{- include "jitsi-meet.turn.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.turn.enabled }}
  TURN_USERNAME: '{{ .Values.turn.xmpp.user | default "turn" | b64enc }}'
  TURN_CREDENTIALS: '{{ default (randAlphaNum 10) .Values.turn.xmpp.password | b64enc }}'
  {{- end }}