{{- if .Values.jvb.metrics.enabled }}
{{- range $shard := until (int .Values.jvb.replicaCount) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%d-metrics" (include "jitsi-meet.jvb.fullname" $) $shard }}
  labels:
    {{ include "jitsi-meet.jvb.labels" $ | nindent 4 }}
    jvb-shard: {{ printf "%s-%d" (include "jitsi-meet.jvb.fullname" $) $shard }}
spec:
  type: ClusterIP
  ports:
    - port: 9888
      protocol: TCP
      name: tcp-metrics
  selector:
    jvb-shard: {{ printf "%s-%d" (include "jitsi-meet.jvb.fullname" $) $shard }}
    {{ include "jitsi-meet.jvb.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
