{{- if and .Values.web.overlay.enabled (eq .Values.web.overlay.mode "v1") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-meet.web.fullname" . }}-proxy
  labels:
    {{- include "jitsi-meet.web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.overlay.proxy.replicas }}
  selector:
    matchLabels:
      {{- include "jitsi-meet.web.proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jitsi-meet.web.proxy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: proxy
          image: {{ .Values.web.overlay.proxy.image.repository }}:{{ .Values.web.overlay.proxy.image.tag }}
          imagePullPolicy: {{ .Values.web.overlay.proxy.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.overlay.proxy.service.port }}
              name: http
          {{- with .Values.web.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.web.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: shared-meet
              mountPath: /usr/share/jitsi-meet
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "jitsi-meet.web.fullname" . }}-proxy
        - name: shared-meet
          persistentVolumeClaim:
            claimName: {{ include "jitsi-meet.web.fullname" . }}-shared-meet
{{- end -}}