{
 "title": "Conférences en cours",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "jvb",
    "label": "JVB",
    "query": {
     "query": "label_values(ape_jitsi_conferences{job=\"apitech-prometheus-exporter\"},jvb_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Statistiques sur la période sélectionnée",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Nombre de participants simultanés",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ape_jitsi_conferences{job=\"apitech-prometheus-exporter\", jvb_name=~\"$jvb\", conf_name!~\"Aucune conférence\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de conférences simultanées",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count((ape_jitsi_conferences{job=\"apitech-prometheus-exporter\", jvb_name=~\"$jvb\", conf_name!~\"Aucune conférence\"}))",
     "legendFormat": "{{jvb_name}}"
    }
   ]
  },
  {
   "title": "Nombre de participants simultanés par JVB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(jvb_name) (ape_jitsi_conferences{job=\"apitech-prometheus-exporter\", jvb_name=~\"$jvb\"})",
     "legendFormat": "{{jvb_name}}"
    }
   ]
  },
  {
   "title": "Nombre de conférences simultanées par JVB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(jvb) (ape_jitsi_conferences{job=\"apitech-prometheus-exporter\", jvb_name=~\"$jvb\", conf_name!~\"Aucune conférence\"})",
     "legendFormat": "{{jvb_name}}"
    }
   ]
  },
  {
   "title": "Code HTTP endpoints JVB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ape_jitsi_jvb_status_code{job=\"apitech-prometheus-exporter\", jvb_name=~\"$jvb\"}",
     "legendFormat": "{{jvb_name}}"
    }
   ]
  },
  { "title": "Statistiques instantanées", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Nombre d'utilisateurs par conférences en cours",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ape_jitsi_conferences{job=~\"apitech-prometheus-exporter\", jvb_name=~\"$jvb\", conf_name!=\"Aucune conférence\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre total de participants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ape_jitsi_conferences{job=\"apitech-prometheus-exporter\", jvb_name=~\"$jvb\"})",
     "legendFormat": "{{conf_name}}"
    }
   ]
  },
  {
   "title": "Nb. de conférences en cours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ape_jitsi_conferences{job=\"apitech-prometheus-exporter\", jvb_name=~\"$jvb\", conf_name!=\"Aucune conférence\"})",
     "legendFormat": "{{conf_name}}"
    }
   ]
  },
  {
   "title": "Conférence en cours avec le plus de participants",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(ape_jitsi_conferences{job=\"apitech-prometheus-exporter\", jvb_name=~\"$jvb\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}