{
 "title": "Jitsi Meet",
 "description": "Tableau de bord pour l’exportateur Jitsi Meet",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(jitsi_conferences, job)"
   }
  ]
 },
 "panels": [
  { "title": "Métriques clés", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Débit descendant",
   "type": "stat",
   "description": "Débit total entrant pour le pont vidéo, en kilobits par seconde.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jitsi_bit_rate_download{job=~\"$job.*\"}"
    }
   ]
  },
  {
   "title": "Débit montant",
   "type": "stat",
   "description": "Débit total sortant pour le pont vidéo, en kilobits par seconde.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jitsi_bit_rate_upload{job=~\"$job.*\"}"
    }
   ]
  },
  {
   "title": "Threads Java",
   "type": "stat",
   "description": "Nombre de threads Java utilisés par le pont vidéo.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jitsi_threads{job=~\"$job.*\"}"
    }
   ]
  },
  {
   "title": "Flux vidéo",
   "type": "stat",
   "description": "Estimation du nombre actuel de flux vidéo transmis par le pont.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jitsi_videostreams{job=~\"$job.*\"}"
    }
   ]
  },
  {
   "title": "Aller-retour moyen (RTT)",
   "type": "stat",
   "description": "Valeur moyenne du RTT sur l’ensemble des flux (en millisecondes).",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jitsi_rtt_aggregate{job=~\"$job.*\"}"
    }
   ]
  },
  {
   "title": "Conférences terminées",
   "type": "stat",
   "description": "Somme des durées de toutes les conférences terminées, en secondes.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jitsi_total_conference_seconds{job=~\"$job.*\"}"
    }
   ]
  },
  {
   "title": "Plus grande conférence",
   "type": "stat",
   "description": "Nombre de participants dans la plus grande conférence actuellement hébergée sur le pont.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(jitsi_largest_conference{job=~\"$job.*\"})"
    }
   ]
  },
  {
   "title": "Nombre total de conférences",
   "type": "stat",
   "description": "Nombre total de conférences créées sur le pont.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jitsi_total_conferences_created{job=~\"$job.*\"}"
    }
   ]
  },
  {
   "title": "Conférences en cours",
   "type": "graph",
   "description": "Nombre actuel de conférences.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_conferences{job=~\"$job.*\"}",
     "legendFormat": "conferences"
    },
    {
     "expr": "jitsi_p2p_conferences{job=~\"$job.*\"}",
     "legendFormat": "p2p conferences"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "description": "Nombre actuel de participants.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_participants{job=~\"$job.*\"}",
     "legendFormat": "participants"
    }
   ]
  },
  {
   "title": "Additional Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Débit global (entrant/sortant)",
     "type": "graph",
     "description": "Débit total entrant/sortant pour le pont vidéo, en kilobits par seconde.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "Kbits" }
     ],
     "targets": [
      {
       "expr": "jitsi_bit_rate_download{job=~\"$job.*\"}",
       "legendFormat": "download"
      },
      {
       "expr": "jitsi_bit_rate_upload{job=~\"$job.*\"}",
       "legendFormat": "upload"
      }
     ]
    },
    {
     "title": "Taux de paquets",
     "type": "graph",
     "description": " The total incoming/outgoing packet rate for the video bridge in packets per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jitsi_packet_rate_download{job=~\"$job.*\"}",
       "legendFormat": "download"
      },
      {
       "expr": "jitsi_packet_rate_upload{job=~\"$job.*\"}",
       "legendFormat": "upload"
      }
     ]
    },
    {
     "title": "Paquets RTP perdus",
     "type": "graph",
     "description": "The fraction of lost incoming RTP packets. This is based on RTP sequence numbers and is relatively accurate.\nThe fraction of lost outgoing RTP packets. This is based on incoming RTCP Receiver Reports, and an attempt to subtract the fraction of packets that were not sent (i.e. were lost before they reached the bridge). Further, this is averaged over all streams of all users as opposed to all packets, so it is not correctly weighted. This is not accurate, but may be a useful metric nonetheless.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jitsi_loss_rate_download{job=~\"$job.*\"}",
       "legendFormat": "download"
      },
      {
       "expr": "jitsi_loss_rate_upload{job=~\"$job.*\"}",
       "legendFormat": "upload"
      }
     ]
    },
    {
     "title": "Gigue moyenne",
     "type": "graph",
     "description": "Expérimental. Valeur moyenne (en millisecondes) de la gigue calculée pour les flux entrants et sortants. Non vérifié.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "jitsi_jitter_aggregate{job=~\"$job.*\"}",
       "legendFormat": "jitter"
      }
     ]
    },
    {
     "title": "Aller-retour moyen (RTT)",
     "type": "graph",
     "description": "Valeur moyenne du RTT sur l’ensemble des flux (en millisecondes).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "jitsi_rtt_aggregate{job=~\"$job.*\"}",
       "legendFormat": "rtt"
      }
     ]
    },
    {
     "title": "Audio/Videochannels",
     "type": "graph",
     "description": "The current number of audio/video channels.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jitsi_audiochannels{job=~\"$job.*\"}",
       "legendFormat": "audiochannels"
      },
      {
       "expr": "jitsi_videochannels{job=~\"$job.*\"}",
       "legendFormat": "videochannels"
      }
     ]
    },
    {
     "title": "Loss-controlled participant-seconds",
     "type": "graph",
     "description": "The rate of participant-seconds that are loss-controlled.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jitsi_total_loss_controlled_participant_seconds{job=~\"$job.*\"}[1m])",
       "legendFormat": "participant-seconds"
      }
     ]
    },
    {
     "title": "Loss-limited participant-seconds",
     "type": "graph",
     "description": "The rate of participant-seconds that are loss-limited.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jitsi_total_loss_limited_participant_seconds{job=~\"$job.*\"}[1m])",
       "legendFormat": "participant-seconds"
      }
     ]
    },
    {
     "title": "Loss-degraded participant-seconds",
     "type": "graph",
     "description": "The rate of participant-seconds that are loss-degraded.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jitsi_total_loss_degraded_participant_seconds{job=~\"$job.*\"}[1m])",
       "legendFormat": "participant-seconds"
      }
     ]
    },
    {
     "title": "Failed Conferences",
     "type": "graph",
     "description": "The rate of failed conferences on the bridge. A conference is marked as failed when all of its channels have failed. A channel is marked as failed if it had no payload activity.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jitsi_total_failed_conferences{job=~\"$job.*\"}[1m])",
       "legendFormat": "failed conferences"
      }
     ]
    },
    {
     "title": "Partially Failed Conferences",
     "type": "graph",
     "description": "The rate of partially failed conferences on the bridge. A conference is marked as partially failed when some of its channels has failed. A channel is marked as failed if it had no payload activity.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jitsi_total_partially_failed_conferences{job=~\"$job.*\"}[1m])",
       "legendFormat": "partially failed conferences"
      }
     ]
    },
    {
     "title": "Sent/Received Messages",
     "type": "graph",
     "description": "The total number messages sent/received through data channels.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jitsi_total_data_channel_messages_received{job=~\"$job.*\"}[1m])",
       "legendFormat": "received"
      },
      {
       "expr": "rate(jitsi_total_data_channel_messages_sent{job=~\"$job.*\"}[1m])",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "Sent/Received Websockets",
     "type": "graph",
     "description": "The total number messages sent/received through COLIBRI web sockets.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jitsi_total_colibri_web_socket_messages_received{job=~\"$job.*\"}[1m])",
       "legendFormat": "received"
      },
      {
       "expr": "rate(jitsi_total_colibri_web_socket_messages_sent{job=~\"$job.*\"}[1m])",
       "legendFormat": "sent"
      }
     ]
    }
   ]
  }
 ]
}