{
 "title": "Jitsi Meet & System",
 "description": "Dashboard for Jitsi Meet Exporter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(jitsi_conferences, job)"
   }
  ]
 },
 "panels": [
  { "title": "Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=~\"$job.*\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',job=~\"$job.*\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{job=~\"$job.*\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=~\"$job.*\"} * 100) / node_memory_MemTotal_bytes{job=~\"$job.*\"})"
    }
   ]
  },
  {
   "title": "Transfered data volume",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_network_receive_bytes_total{job=~\"$job.*\"})*(9.31*10^-10)",
     "legendFormat": "Incoming "
    },
    {
     "expr": "sum(node_network_transmit_bytes_total{job=~\"$job.*\"})*(9.31*10^-10)",
     "legendFormat": "Outgoing"
    },
    {
     "expr": "(sum(node_network_receive_bytes_total{job=~\"$job.*\"})+sum(node_network_transmit_bytes_total{job=~\"$job.*\"}))*(9.31*10^-10)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Bitrate Download",
   "type": "stat",
   "description": "The total incoming bitrate for the video bridge in kilobits per second.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jitsi_bit_rate_download{job=~\"$job.*\"}"
    }
   ]
  },
  {
   "title": "Bitrate Upload",
   "type": "stat",
   "description": "The total outgoing bitrate for the video bridge in kilobits per second.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jitsi_bit_rate_upload{job=~\"$job.*\"}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "The number of Java threads that the video bridge is using.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jitsi_threads{job=~\"$job.*\"}"
    }
   ]
  },
  {
   "title": "Videostreams",
   "type": "stat",
   "description": "An estimation of the number of current video streams forwarded by the bridge.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jitsi_videostreams{job=~\"$job.*\"}"
    }
   ]
  },
  {
   "title": "RTT",
   "type": "stat",
   "description": "An average value (in milliseconds) of the RTT across all streams.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jitsi_rtt_aggregate{job=~\"$job.*\"}"
    }
   ]
  },
  {
   "title": "Completed Conferences",
   "type": "stat",
   "description": "The sum of the lengths of all completed conferences, in seconds.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jitsi_total_conference_seconds{job=~\"$job.*\"}"
    }
   ]
  },
  {
   "title": "Biggest Conference",
   "type": "stat",
   "description": "The number of participants in the largest conference currently hosted on the bridge.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(jitsi_largest_conference{job=~\"$job.*\"})"
    }
   ]
  },
  {
   "title": "Total Conferences",
   "type": "stat",
   "description": "The total number of conferences created on the bridge.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jitsi_total_conferences_created{job=~\"$job.*\"}"
    }
   ]
  },
  {
   "title": "Conferences",
   "type": "graph",
   "description": "The current number of conferences.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_conferences{job=~\"$job.*\"}",
     "legendFormat": "conferences"
    },
    {
     "expr": "jitsi_p2p_conferences{job=~\"$job.*\"}",
     "legendFormat": "p2p conferences"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "description": "The current number of participants.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_participants{job=~\"$job.*\"}",
     "legendFormat": "participants"
    }
   ]
  },
  {
   "title": "Additional Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bitrate",
     "type": "graph",
     "description": "The total incoming/outgoing bitrate for the video bridge in kilobits per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "Kbits" }
     ],
     "targets": [
      {
       "expr": "jitsi_bit_rate_download{job=~\"$job.*\"}",
       "legendFormat": "download"
      },
      {
       "expr": "jitsi_bit_rate_upload{job=~\"$job.*\"}",
       "legendFormat": "upload"
      }
     ]
    },
    {
     "title": "Package Rate",
     "type": "graph",
     "description": " The total incoming/outgoing packet rate for the video bridge in packets per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jitsi_packet_rate_download{job=~\"$job.*\"}",
       "legendFormat": "download"
      },
      {
       "expr": "jitsi_packet_rate_upload{job=~\"$job.*\"}",
       "legendFormat": "upload"
      }
     ]
    },
    {
     "title": "Lost RTP packets",
     "type": "graph",
     "description": "The fraction of lost incoming RTP packets. This is based on RTP sequence numbers and is relatively accurate.\nThe fraction of lost outgoing RTP packets. This is based on incoming RTCP Receiver Reports, and an attempt to subtract the fraction of packets that were not sent (i.e. were lost before they reached the bridge). Further, this is averaged over all streams of all users as opposed to all packets, so it is not correctly weighted. This is not accurate, but may be a useful metric nonetheless.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jitsi_loss_rate_download{job=~\"$job.*\"}",
       "legendFormat": "download"
      },
      {
       "expr": "jitsi_loss_rate_upload{job=~\"$job.*\"}",
       "legendFormat": "upload"
      }
     ]
    },
    {
     "title": "Jitter Aggregate",
     "type": "graph",
     "description": "Experimental. An average value (in milliseconds) of the jitter calculated for incoming and outgoing streams. This hasn't been tested and it is currently not known whether the values are correct or not.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "jitsi_jitter_aggregate{job=~\"$job.*\"}",
       "legendFormat": "jitter"
      }
     ]
    },
    {
     "title": "RTT",
     "type": "graph",
     "description": "An average value (in milliseconds) of the RTT across all streams.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "jitsi_rtt_aggregate{job=~\"$job.*\"}",
       "legendFormat": "rtt"
      }
     ]
    },
    {
     "title": "Audio/Videochannels",
     "type": "graph",
     "description": "The current number of audio/video channels.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jitsi_audiochannels{job=~\"$job.*\"}",
       "legendFormat": "audiochannels"
      },
      {
       "expr": "jitsi_videochannels{job=~\"$job.*\"}",
       "legendFormat": "videochannels"
      }
     ]
    },
    {
     "title": "Loss-controlled participant-seconds",
     "type": "graph",
     "description": "The rate of participant-seconds that are loss-controlled.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jitsi_total_loss_controlled_participant_seconds{job=~\"$job.*\"}[1m])",
       "legendFormat": "participant-seconds"
      }
     ]
    },
    {
     "title": "Loss-limited participant-seconds",
     "type": "graph",
     "description": "The rate of participant-seconds that are loss-limited.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jitsi_total_loss_limited_participant_seconds{job=~\"$job.*\"}[1m])",
       "legendFormat": "participant-seconds"
      }
     ]
    },
    {
     "title": "Loss-degraded participant-seconds",
     "type": "graph",
     "description": "The rate of participant-seconds that are loss-degraded.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jitsi_total_loss_degraded_participant_seconds{job=~\"$job.*\"}[1m])",
       "legendFormat": "participant-seconds"
      }
     ]
    },
    {
     "title": "Failed Conferences",
     "type": "graph",
     "description": "The rate of failed conferences on the bridge. A conference is marked as failed when all of its channels have failed. A channel is marked as failed if it had no payload activity.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jitsi_total_failed_conferences{job=~\"$job.*\"}[1m])",
       "legendFormat": "failed conferences"
      }
     ]
    },
    {
     "title": "Partially Failed Conferences",
     "type": "graph",
     "description": "The rate of partially failed conferences on the bridge. A conference is marked as partially failed when some of its channels has failed. A channel is marked as failed if it had no payload activity.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jitsi_total_partially_failed_conferences{job=~\"$job.*\"}[1m])",
       "legendFormat": "partially failed conferences"
      }
     ]
    },
    {
     "title": "Sent/Received Messages",
     "type": "graph",
     "description": "The total number messages sent/received through data channels.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jitsi_total_data_channel_messages_received{job=~\"$job.*\"}[1m])",
       "legendFormat": "received"
      },
      {
       "expr": "rate(jitsi_total_data_channel_messages_sent{job=~\"$job.*\"}[1m])",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "Sent/Received Websockets",
     "type": "graph",
     "description": "The total number messages sent/received through COLIBRI web sockets.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jitsi_total_colibri_web_socket_messages_received{job=~\"$job.*\"}[1m])",
       "legendFormat": "received"
      },
      {
       "expr": "rate(jitsi_total_colibri_web_socket_messages_sent{job=~\"$job.*\"}[1m])",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "Videobridge Stress Level",
     "type": "graph",
     "description": "Stress Level reported to Jicofo by the videobridge.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jitsi_stress_level{job=~\"$job.*\"}",
       "legendFormat": "stress level"
      }
     ]
    }
   ]
  }
 ]
}